### PR TITLE
 Tidied HTML file

### PR DESCRIPTION
**Pull request by jon-atto-bennett**
Sam's HTML file after tidying indentation.

### CODE REVIEW

**Review by todddrinkwater — COMMENTED** [review]
Code is indented perfectly. Want to to approve this?

**Comment by jon-atto-bennett** [comment]
Cheers Todd be my guest 👍

**Review by todddrinkwater — APPROVED** [review]
No issues with code. Approved!

**Comment by jon-atto-bennett** [comment]
Hi Todd I have merged the commit now so the branch can be deleted. Cheers

**Pull request merged**
